// Exercise preview images sourced from the free-exercise-db (CC0 licence).
// https://github.com/yuhonas/free-exercise-db

const BASE = "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises";
const WIKI = "https://upload.wikimedia.org/wikipedia/commons";

export const EXERCISE_IMAGES: Record<string, string> = {

  // ── Push: Chest ────────────────────────────────────────────────────────────
  "Bench Press":               `${BASE}/Barbell_Bench_Press_-_Medium_Grip/0.jpg`,
  "Incline Bench Press":       `${BASE}/Barbell_Incline_Bench_Press_-_Medium_Grip/0.jpg`,
  "Decline Bench Press":       `${BASE}/Decline_Barbell_Bench_Press/0.jpg`,
  "Dumbbell Bench Press":      `${BASE}/Dumbbell_Bench_Press/0.jpg`,
  "Incline Dumbbell Press":    `${BASE}/Incline_Dumbbell_Press/0.jpg`,
  "Dumbbell Fly":              `${BASE}/Dumbbell_Flyes/0.jpg`,
  "Incline Dumbbell Fly":      `${BASE}/Incline_Dumbbell_Flyes/0.jpg`,
  "Decline Dumbbell Fly":      `${BASE}/Decline_Dumbbell_Flyes/0.jpg`,
  "Cable Fly":                 `${BASE}/Cable_Crossover/0.jpg`,
  "Low Cable Fly":             `${BASE}/Cable_Crossover/0.jpg`,
  "High Cable Fly":            `${BASE}/Cable_Crossover/0.jpg`,
  "Machine Chest Press":       `${BASE}/Dumbbell_Bench_Press/0.jpg`,
  "Smith Machine Bench Press": `${BASE}/Barbell_Bench_Press_-_Medium_Grip/0.jpg`,
  "Pec Deck":                  `${BASE}/Pec_Dec_Fly/0.jpg`,
  "Push-Ups":                  `${BASE}/Pushups/0.jpg`,
  "Floor Press":               `${BASE}/Barbell_Floor_Press/0.jpg`,
  "Landmine Press":            `${BASE}/Barbell_Shoulder_Press/0.jpg`,
  "Dumbbell Pullover":         `${BASE}/Dumbbell_Pullover/0.jpg`,
  "Svend Press":               `${BASE}/Barbell_Bench_Press_-_Medium_Grip/0.jpg`,

  // ── Push: Shoulders ───────────────────────────────────────────────────────
  "Overhead Press":            `${BASE}/Barbell_Shoulder_Press/0.jpg`,
  "Dumbbell Shoulder Press":   `${BASE}/Seated_Dumbbell_Press/0.jpg`,
  "Machine Shoulder Press":    `${BASE}/Seated_Dumbbell_Press/0.jpg`,
  "Arnold Press":              `${BASE}/Arnold_Dumbbell_Press/0.jpg`,
  "Push Press":                `${BASE}/Push_Press/0.jpg`,
  "Behind The Neck Press":     `${BASE}/Behind_The_Neck_Barbell_Press/0.jpg`,
  "Z Press":                   `${BASE}/Seated_Dumbbell_Press/0.jpg`,
  "Bradford Press":            `${BASE}/Barbell_Shoulder_Press/0.jpg`,
  "Lateral Raises":            `${BASE}/Side_Lateral_Raise/0.jpg`,
  "Cable Lateral Raises":      `${BASE}/One-Arm_Side_Laterals/0.jpg`,
  "Landmine Lateral Raise":    `${BASE}/Side_Lateral_Raise/0.jpg`,
  "Front Raises":              `${BASE}/Alternating_Deltoid_Raise/0.jpg`,
  "Cable Front Raise":         `${BASE}/Alternating_Deltoid_Raise/0.jpg`,
  "Upright Row":               `${BASE}/Barbell_Upright_Row/0.jpg`,
  "Cable Upright Row":         `${BASE}/Barbell_Upright_Row/0.jpg`,
  "Rear Delt Fly":             `${BASE}/Bent_Over_Dumbbell_Rear_Delt_Raise_-_With_Head_On_Bench/0.jpg`,
  "Reverse Fly":               `${BASE}/Bent_Over_Dumbbell_Rear_Delt_Raise_-_With_Head_On_Bench/0.jpg`,
  "Bent Over Lateral Raise":   `${BASE}/Bent_Over_Dumbbell_Rear_Delt_Raise_-_With_Head_On_Bench/0.jpg`,
  "Cable Face Pull":           `${BASE}/Face_Pull/0.jpg`,
  "Cable Rear Delt Fly":       `${BASE}/Bent_Over_Dumbbell_Rear_Delt_Raise_-_With_Head_On_Bench/0.jpg`,

  // ── Push: Triceps ─────────────────────────────────────────────────────────
  "Tricep Pushdown":                    `${BASE}/Triceps_Pushdown/0.jpg`,
  "Rope Tricep Pushdown":               `${BASE}/Tricep_Rope_Pushdown/0.jpg`,
  "Reverse Grip Tricep Pushdown":       `${BASE}/Triceps_Pushdown/0.jpg`,
  "Single Arm Tricep Pushdown":         `${BASE}/Triceps_Pushdown/0.jpg`,
  "Skull Crushers":                     `${BASE}/Lying_Triceps_Press/0.jpg`,
  "Close Grip Bench Press":             `${BASE}/Close-Grip_Barbell_Bench_Press/0.jpg`,
  "Overhead Tricep Extension":          `${BASE}/Cable_Rope_Overhead_Triceps_Extension/0.jpg`,
  "Cable Overhead Tricep Extension":    `${BASE}/Cable_Rope_Overhead_Triceps_Extension/0.jpg`,
  "Dumbbell Overhead Tricep Extension": `${BASE}/Dumbbell_One_Arm_Triceps_Extension/0.jpg`,
  "Tricep Dips":                        `${BASE}/Dips_-_Triceps_Version/0.jpg`,
  "Bench Dips":                         `${BASE}/Bench_Dips/0.jpg`,
  "Diamond Push-Ups":                   `${BASE}/Pushups/0.jpg`,
  "Tricep Kickback":                    `${BASE}/Dumbbell_Tricep_Kickbacks/0.jpg`,
  "JM Press":                           `${BASE}/Lying_Triceps_Press/0.jpg`,
  "Tate Press":                         `${BASE}/Lying_Triceps_Press/0.jpg`,
  "Machine Tricep Extension":           `${BASE}/Triceps_Pushdown/0.jpg`,

  // ── Pull: Back ────────────────────────────────────────────────────────────
  "Deadlift":               `${BASE}/Barbell_Deadlift/0.jpg`,
  "Rack Pull":              `${BASE}/Barbell_Deadlift/0.jpg`,
  "Barbell Row":            `${BASE}/Bent_Over_Barbell_Row/0.jpg`,
  "Pendlay Row":            `${BASE}/Bent_Over_Barbell_Row/0.jpg`,
  "Meadows Row":            `${BASE}/T-Bar_Row_with_Handle/0.jpg`,
  "Seal Row":               `${BASE}/Bent_Over_Barbell_Row/0.jpg`,
  "Kroc Row":               `${BASE}/One-Arm_Dumbbell_Row/0.jpg`,
  "Incline Dumbbell Row":   `${BASE}/Dumbbell_Incline_Row/0.jpg`,
  "Single Arm Dumbbell Row":`${BASE}/One-Arm_Dumbbell_Row/0.jpg`,
  "Renegade Row":           `${BASE}/One-Arm_Dumbbell_Row/0.jpg`,
  "T-Bar Row":              `${BASE}/T-Bar_Row_with_Handle/0.jpg`,
  "Chest Supported Row":    `${BASE}/Dumbbell_Incline_Row/0.jpg`,
  "Machine Row":            `${BASE}/Seated_Cable_Rows/0.jpg`,
  "Pull-Ups":               `${BASE}/Pullups/0.jpg`,
  "Chin-Ups":               `${BASE}/Chin_Up/0.jpg`,
  "Weighted Pull-Ups":      `${BASE}/Pullups/0.jpg`,
  "Lat Pulldown":           `${BASE}/Wide-Grip_Lat_Pulldown/0.jpg`,
  "Underhand Lat Pulldown": `${BASE}/Underhand_Cable_Pulldowns/0.jpg`,
  "Seated Cable Row":       `${BASE}/Seated_Cable_Rows/0.jpg`,
  "Wide Grip Cable Row":    `${BASE}/Seated_Cable_Rows/0.jpg`,
  "Straight Arm Pulldown":  `${BASE}/Straight-Arm_Pulldown/0.jpg`,
  "Cable Pullover":         `${BASE}/Straight-Arm_Pulldown/0.jpg`,
  "Face Pulls":             `${BASE}/Face_Pull/0.jpg`,
  "Good Mornings":          `${BASE}/Good_Morning/0.jpg`,
  "Back Extension":         `${BASE}/Hyperextensions_-_Back_Extensions/0.jpg`,

  // ── Pull: Biceps ──────────────────────────────────────────────────────────
  "Barbell Curl":         `${BASE}/Barbell_Curl/0.jpg`,
  "EZ Bar Curl":          `${BASE}/EZ-Bar_Curl/0.jpg`,
  "21s Barbell Curl":     `${BASE}/Barbell_Curl/0.jpg`,
  "Dumbbell Curl":        `${BASE}/Dumbbell_Alternate_Bicep_Curl/0.jpg`,
  "Incline Dumbbell Curl":`${BASE}/Alternate_Incline_Dumbbell_Curl/0.jpg`,
  "Concentration Curl":   `${BASE}/Concentration_Curls/0.jpg`,
  "Spider Curl":          `${BASE}/Barbell_Curl/0.jpg`,
  "Drag Curl":            `${BASE}/Barbell_Curl/0.jpg`,
  "Hammer Curl":          `${BASE}/Alternate_Hammer_Curl/0.jpg`,
  "Cross Body Hammer Curl":`${BASE}/Alternate_Hammer_Curl/0.jpg`,
  "Zottman Curl":         `${BASE}/Dumbbell_Alternate_Bicep_Curl/0.jpg`,
  "Reverse Curl":         `${BASE}/Barbell_Curl/0.jpg`,
  "Preacher Curl":        `${BASE}/Preacher_Curl/0.jpg`,
  "Machine Curl":         `${BASE}/Preacher_Curl/0.jpg`,
  "Cable Curl":           `${BASE}/Standing_Biceps_Cable_Curl/0.jpg`,
  "Bayesian Cable Curl":  `${BASE}/Standing_Biceps_Cable_Curl/0.jpg`,
  "Cable Hammer Curl":    `${BASE}/Alternate_Hammer_Curl/0.jpg`,

  // ── Legs: Quads / Hamstrings ──────────────────────────────────────────────
  "Barbell Squat":              `${BASE}/Barbell_Squat/0.jpg`,
  "Front Squat":                `${BASE}/Barbell_Front_Squat/0.jpg`,
  "Box Squat":                  `${BASE}/Barbell_Box_Squat/0.jpg`,
  "Pause Squat":                `${BASE}/Barbell_Squat/0.jpg`,
  "Tempo Squat":                `${BASE}/Barbell_Squat/0.jpg`,
  "Overhead Squat":             `${BASE}/Barbell_Squat/0.jpg`,
  "Zercher Squat":              `${BASE}/Barbell_Squat/0.jpg`,
  "Jefferson Squat":            `${BASE}/Barbell_Squat/0.jpg`,
  "Safety Bar Squat":           `${BASE}/Barbell_Squat/0.jpg`,
  "Smith Machine Squat":        `${BASE}/Barbell_Squat/0.jpg`,
  "Goblet Squat":               `${BASE}/Goblet_Squat/0.jpg`,
  "Sumo Squat":                 `${BASE}/Barbell_Squat/0.jpg`,
  "Hack Squat":                 `${BASE}/Barbell_Hack_Squat/0.jpg`,
  "Leg Press":                  `${BASE}/Leg_Press/0.jpg`,
  "Leg Extension":              `${BASE}/Leg_Extensions/0.jpg`,
  "Leg Curl":                   `${BASE}/Lying_Leg_Curls/0.jpg`,
  "Seated Leg Curl":            `${BASE}/Lying_Leg_Curls/0.jpg`,
  "Standing Leg Curl":          `${BASE}/Lying_Leg_Curls/0.jpg`,
  "Nordic Hamstring Curl":      `${BASE}/Lying_Leg_Curls/0.jpg`,
  "Romanian Deadlift":          `${BASE}/Romanian_Deadlift/0.jpg`,
  "Stiff Leg Deadlift":         `${BASE}/Romanian_Deadlift/0.jpg`,
  "Single Leg Romanian Deadlift":`${BASE}/Romanian_Deadlift/0.jpg`,
  "Bulgarian Split Squat":      `${BASE}/Split_Squat_with_Dumbbells/0.jpg`,
  "Split Squat":                `${BASE}/Split_Squat_with_Dumbbells/0.jpg`,
  "Walking Lunges":             `${BASE}/Barbell_Walking_Lunge/0.jpg`,
  "Dumbbell Lunges":            `${BASE}/Dumbbell_Lunges/0.jpg`,
  "Reverse Lunges":             `${BASE}/Barbell_Reverse_Lunge/0.jpg`,
  "Lateral Lunges":             `${BASE}/Dumbbell_Lunges/0.jpg`,
  "Step-Ups":                   `${BASE}/Barbell_Step_Ups/0.jpg`,
  "Dumbbell Step-Ups":          `${BASE}/Barbell_Step_Ups/0.jpg`,
  "Sissy Squat":                `${BASE}/Leg_Extensions/0.jpg`,
  "Calf Raises":                `${BASE}/Barbell_Seated_Calf_Raise/0.jpg`,
  "Seated Calf Raise":          `${BASE}/Barbell_Seated_Calf_Raise/0.jpg`,
  "Single Leg Calf Raise":      `${BASE}/Barbell_Seated_Calf_Raise/0.jpg`,
  "Leg Press Calf Raise":       `${BASE}/Barbell_Seated_Calf_Raise/0.jpg`,
  "Cable Pull-Through":         `${BASE}/Sumo_Deadlift/0.jpg`,

  // ── Legs: Glutes ──────────────────────────────────────────────────────────
  "Hip Thrust":              `${BASE}/Barbell_Hip_Thrust/0.jpg`,
  "Banded Hip Thrust":       `${BASE}/Barbell_Hip_Thrust/0.jpg`,
  "Single Leg Hip Thrust":   `${BASE}/Barbell_Hip_Thrust/0.jpg`,
  "Deficit Hip Thrust":      `${BASE}/Barbell_Hip_Thrust/0.jpg`,
  "Smith Machine Hip Thrust":`${BASE}/Barbell_Hip_Thrust/0.jpg`,
  "Sumo Deadlift":           `${BASE}/Sumo_Deadlift/0.jpg`,
  "Cable Kickback":          `${BASE}/One-Legged_Cable_Kickback/0.jpg`,
  "Glute Bridge":            `${BASE}/Barbell_Glute_Bridge/0.jpg`,
  "Banded Glute Bridge":     `${BASE}/Barbell_Glute_Bridge/0.jpg`,
  "Single Leg Glute Bridge": `${BASE}/Barbell_Glute_Bridge/0.jpg`,
  "Donkey Kicks":            `${BASE}/One-Legged_Cable_Kickback/0.jpg`,
  "Fire Hydrants":           `${WIKI}/b/b8/Squat_side_view.jpg`,
  "Side-Lying Clamshell":    `${BASE}/Lying_Glute/0.jpg`,
  "Reverse Hyperextension":  `${BASE}/Hyperextensions_-_Back_Extensions/0.jpg`,
  "Frog Pumps":              `${BASE}/Barbell_Glute_Bridge/0.jpg`,

  // ── Core ──────────────────────────────────────────────────────────────────
  "Plank":                   `${BASE}/Plank/0.jpg`,
  "Side Plank":              `${BASE}/Side_Plank/0.jpg`,
  "Hollow Body Hold":        `${BASE}/Plank/0.jpg`,
  "Dead Bug":                `${BASE}/Plank/0.jpg`,
  "Ab Crunch":               `${BASE}/Crunches/0.jpg`,
  "Decline Crunch":          `${BASE}/Decline_Crunch/0.jpg`,
  "Reverse Crunch":          `${BASE}/Reverse_Crunch/0.jpg`,
  "Bicycle Crunch":          `${BASE}/Bicycle_Crunch/0.jpg`,
  "Weighted Crunch":         `${BASE}/Crunches/0.jpg`,
  "Cable Crunch":            `${BASE}/Kneeling_Cable_Crunch/0.jpg`,
  "Decline Weighted Crunch": `${BASE}/Decline_Crunch/0.jpg`,
  "Leg Raises":              `${BASE}/Flat_Bench_Lying_Leg_Raise/0.jpg`,
  "Hanging Leg Raises":      `${BASE}/Hanging_Leg-Hip_Raise/0.jpg`,
  "Toes To Bar":             `${BASE}/Hanging_Leg-Hip_Raise/0.jpg`,
  "L-Sit":                   `${BASE}/Plank/0.jpg`,
  "Dragon Flag":             `${BASE}/Plank/0.jpg`,
  "Ab Rollout":              `${BASE}/Stability_Ball_Rollout/0.jpg`,
  "Russian Twist":           `${BASE}/Russian_Twist/0.jpg`,
  "V-Ups":                   `${BASE}/Crunches/0.jpg`,
  "Flutter Kicks":           `${BASE}/Flat_Bench_Lying_Leg_Raise/0.jpg`,
  "Mountain Climbers":       `${BASE}/Mountain_Climbers/0.jpg`,
  "Pallof Press":            `${BASE}/Face_Pull/0.jpg`,
  "Woodchop":                `${BASE}/Triceps_Pushdown/0.jpg`,
  "Landmine Rotation":       `${BASE}/Barbell_Deadlift/0.jpg`,
};
